In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

import warnings
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv(r"D:\Data science by SRK\stroke_prediction.csv")

# Attribute Information
1.
id: unique identifier2.
gender: "Male", "Female" or "Other3."
age: age of the patie4.nt
hypertension: 0 if the patient doesn't have hypertension, 1 if the patient has hypertens5.ion
heart_disease: 0 if the patient doesn't have any heart diseases, 1 if the patient has a heart dis6.ease
ever_married: "No" or 7."Yes"
work_type: "children", "Govt_jov", "Never_worked", "Private" or "Self-emp8.loyed"
Residence_type: "Rural" or 9."Urban"
avg_glucose_level: average glucose level 10.in blood
bmi: body m11.ass index
smoking_status: "formerly smoked", "never smoked", "smokes" or 12."Unknown"*
stroke: 1 if the patient had a stroke or 0 if not
*Note: "Unknown" in smoking_status means that the information is unavailable for this patient

In [62]:
data

id  gender             age hypertension heart_disease ever_married  \
0      30669    Male           child           NO            NO           No   
1      30468    Male     middle_aged          YES            NO          Yes   
2      16523  Female           child           NO            NO           No   
3      56543  Female  senior_citizen           NO            NO          Yes   
4      46136    Male         teenger           NO            NO           No   
...      ...     ...             ...          ...           ...          ...   
43395  56196  Female           child           NO            NO           No   
43396   5450  Female     middle_aged           NO            NO          Yes   
43397  28375  Female  senior_citizen          YES            NO          Yes   
43398  27973    Male     middle_aged           NO            NO          Yes   
43399  36271  Female  senior_citizen           NO            NO          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0          children          Rural              95.12  18.0     never smoked   
1           Private          Urban              87.96  39.2     never smoked   
2           Private          Urban             110.89  17.6     never smoked   
3           Private          Rural              69.04  35.9  formerly smoked   
4      Never_worked          Rural             161.28  19.1     never smoked   
...             ...            ...                ...   ...              ...   
43395      children          Urban              58.64  20.4     never smoked   
43396      Govt_job          Urban             213.61  55.4  formerly smoked   
43397       Private          Urban              91.94  28.9  formerly smoked   
43398       Private          Urban              99.16  33.2     never smoked   
43399       Private          Urban              79.48  20.6     never smoked   

      stroke  
0         NO  
1         NO  
2         NO  
3         NO  
4         NO  
...      ...  
43395     NO  
43396     NO  
43397     NO  
43398     NO  
43399     NO  

[43400 rows x 12 columns]

In [65]:
# Cheaking Missing (NaN) Values:
data.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [12]:
data['hypertension'] = data['hypertension'].replace({0:'NO',1:'YES'})

In [13]:
data['heart_disease'] = data['heart_disease'].replace({0:'NO',1:'YES'})

In [14]:
data['stroke'] = data['stroke'].replace({0:'NO',1:'YES'})

In [15]:
data.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [66]:
data.to_csv('stroke_predictionf.csv', index=False)

In [44]:
continous=['id','avg_glucose_level','bmi']

discrete_categorical =['gender','hypertension','heart_disease','ever_married','work_type','Residence_type','smoking_status','stroke','age']



In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43400 entries, 0 to 43399
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   id                 43400 non-null  int64   
 1   gender             43400 non-null  object  
 2   age                43400 non-null  category
 3   hypertension       43400 non-null  object  
 4   heart_disease      43400 non-null  object  
 5   ever_married       43400 non-null  object  
 6   work_type          43400 non-null  object  
 7   Residence_type     43400 non-null  object  
 8   avg_glucose_level  43400 non-null  float64 
 9   bmi                41938 non-null  float64 
 10  smoking_status     30108 non-null  object  
 11  stroke             43400 non-null  object  
dtypes: category(1), float64(2), int64(1), object(8)
memory usage: 3.7+ MB


In [63]:
data[continous].describe()

id  avg_glucose_level           bmi
count  43400.000000       43400.000000  43400.000000
mean   36326.142350         104.482750     28.605038
std    21072.134879          43.111751      7.638023
min        1.000000          55.000000     10.100000
25%    18038.500000          77.540000     23.400000
50%    36351.500000          91.580000     28.100000
75%    54514.250000         112.070000     32.600000
max    72943.000000         291.050000     97.600000

In [64]:
data[discrete_categorical].describe()

gender hypertension heart_disease ever_married work_type  \
count    43400        43400         43400        43400     43400   
unique       3            2             2            2         5   
top     Female           NO            NO          Yes   Private   
freq     25665        39339         41338        27938     24834   

       Residence_type smoking_status stroke          age  
count           43400          43400  43400        43400  
unique              2              3      2            5  
top             Urban   never smoked     NO  middle_aged  
freq            21756          29345  42617        18653

In [14]:
data['id'].unique()

array([30669, 30468, 16523, ..., 28375, 27973, 36271], dtype=int64)

In [15]:
data['id'].value_counts()

id
30669    1
20384    1
44344    1
13843    1
10813    1
        ..
64649    1
13377    1
64545    1
52084    1
36271    1
Name: count, Length: 43400, dtype: int64

In [19]:
data['gender'].unique()

array(['Male', 'Female', 'Transgender'], dtype=object)

In [20]:
data['gender'].value_counts()

gender
Female         25665
Male           17724
Transgender       11
Name: count, dtype: int64

In [ ]:
crosstab_result = pd.crosstab(df['column1'], df['column2'])

In [69]:
pd.crosstab(data['gender'],data['stroke'])

stroke          NO  YES
gender                 
Female       25234  431
Male         17372  352
Transgender     11    0

In [70]:
pd.crosstab(data['age'],data['stroke'])

stroke             NO  YES
age                       
child            5325    1
teenger          3184    1
young_adult      5723    2
middle_aged     18453  200
senior_citizen   9932  579

In [71]:
pd.crosstab(data['ever_married'],data['stroke'])

stroke           NO  YES
ever_married            
No            15382   80
Yes           27235  703

In [74]:
pd.crosstab(data['heart_disease'],data['stroke'])

stroke            NO  YES
heart_disease            
NO             40732  606
YES             1885  177

In [75]:
pd.crosstab(data['work_type'],data['stroke'])

stroke            NO  YES
work_type                
Govt_job        5351   89
Never_worked     177    0
Private        24393  441
Self_employed   6542  251
children        6154    2

In [76]:
pd.crosstab(data['Residence_type'],data['stroke'])

stroke             NO  YES
Residence_type            
Rural           21260  384
Urban           21357  399

In [77]:
pd.crosstab(data['smoking_status'],data['stroke'])

stroke              NO  YES
smoking_status             
formerly smoked   7272  221
never smoked     28916  429
smokes            6429  133

In [18]:
data['gender'] = data['gender'].replace({'Other':'Transgender'})

In [21]:
data['age'].unique()

['child', 'middle_aged', 'senior_citizen', 'teenger', 'young_adult']
Categories (5, object): ['child' < 'teenger' < 'young_adult' < 'middle_aged' < 'senior_citizen']

In [22]:
data['age'].value_counts()

age
middle_aged       18653
senior_citizen    10511
young_adult        5725
child              5326
teenger            3185
Name: count, dtype: int64

In [7]:
data['age']=pd.cut(data['age'],
                   bins=[0,12,19,30,60,90],
                labels=['child','teenger','young_adult','middle_aged','senior_citizen'])

In [23]:
data['hypertension'].unique()

array(['NO', 'YES'], dtype=object)

In [24]:
data['hypertension'].value_counts()

hypertension
NO     39339
YES     4061
Name: count, dtype: int64

In [25]:
data['heart_disease'].unique()

array(['NO', 'YES'], dtype=object)

In [26]:
data['heart_disease'].value_counts()

heart_disease
NO     41338
YES     2062
Name: count, dtype: int64

In [27]:
data['ever_married'].unique()

array(['No', 'Yes'], dtype=object)

In [28]:
data['ever_married'].value_counts()

ever_married
Yes    27938
No     15462
Name: count, dtype: int64

In [31]:
data['work_type'].unique()

array(['children', 'Private', 'Never_worked', 'Self_employed', 'Govt_job'],
      dtype=object)

In [32]:
data['work_type'].value_counts()

work_type
Private          24834
Self_employed     6793
children          6156
Govt_job          5440
Never_worked       177
Name: count, dtype: int64

In [30]:
data['work_type'] = data['work_type'].replace({'Self-employed':'Self_employed'})

In [33]:
data['Residence_type'].unique()

array(['Rural', 'Urban'], dtype=object)

In [34]:
data['Residence_type'].value_counts()

Residence_type
Urban    21756
Rural    21644
Name: count, dtype: int64

In [35]:
data['avg_glucose_level'].unique()

array([ 95.12,  87.96, 110.89, ..., 182.45, 121.45, 132.22])

In [36]:
data['avg_glucose_level'].value_counts()

avg_glucose_level
82.71     19
87.07     18
72.53     18
83.92     17
84.49     17
          ..
144.15     1
119.98     1
188.26     1
252.75     1
132.22     1
Name: count, Length: 12543, dtype: int64

In [56]:
data['bmi'].unique()

array([18.        , 39.2       , 17.6       , 35.9       , 19.1       ,
       50.1       , 17.7       , 27.        , 32.3       , 54.6       ,
       35.        , 22.        , 39.4       , 26.1       , 42.4       ,
       33.        , 19.7       , 22.5       , 24.6       , 25.2       ,
       41.8       , 60.9       , 31.5       , 27.3       , 23.7       ,
       24.5       , 28.4       , 26.9       , 26.7       , 31.2       ,
       25.        , 25.4       , 27.5       , 16.        , 31.6       ,
       25.1       , 30.9       , 24.8       , 23.4       , 29.4       ,
       18.3       , 20.        , 19.5       , 36.        , 27.7       ,
       28.5       , 26.8       , 33.6       , 29.1       , 34.9       ,
       35.3       , 26.4       , 40.1       , 43.1       , 36.7       ,
       29.3       , 21.2       , 36.6       , 21.4       , 27.9       ,
       34.3       , 31.        , 38.7       , 27.6       , 16.5       ,
       22.8       , 35.4       , 24.3       , 25.7       , 21.9 

In [57]:
data['bmi'].value_counts()

bmi
28.605038    1462
27.700000     271
27.600000     267
26.800000     266
26.100000     265
             ... 
59.100000       1
64.000000       1
56.100000       1
56.900000       1
89.000000       1
Name: count, Length: 556, dtype: int64

In [ ]:
pd.crosstab(data['age'],data['stroke'])

In [51]:
data['smoking_status'].unique()

array(['never smoked', 'formerly smoked', 'smokes'], dtype=object)

In [ ]:
# missing values Treatment

In [50]:
data['smoking_status']=data['smoking_status'].fillna(data['smoking_status'].mode()[0])

In [61]:
data['bmi'] = data['bmi'].fillna(data['bmi'].median())

In [52]:
data['smoking_status'].value_counts()

smoking_status
never smoked       29345
formerly smoked     7493
smokes              6562
Name: count, dtype: int64

In [41]:
data['stroke'].unique()

array(['NO', 'YES'], dtype=object)

In [42]:
data['stroke'].value_counts()

stroke
NO     42617
YES      783
Name: count, dtype: int64